# Etapa de build
FROM golang:1.23
WORKDIR /app

# Copia arquivos de dependência
COPY go.mod go.sum ./

# Baixa todas as dependências
RUN go mod download
# Copia o código-fonte e os arquivos do protocolo gRPC
COPY . .

# Compila o serviço específico
RUN go build -o produtor-de-farinha flour.go

# Porta em que o serviço escuta
EXPOSE 50053

# Executa o serviço
CMD ["./produtor-de-farinha"]
