FROM golang:1.23 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o client_carga_sequencial client_carga_sequencial.go
WORKDIR /app
CMD ["./client_carga_sequencial"]