FROM golang:1.23 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o client client.go

# Define o diretório de trabalho e executa o cliente
WORKDIR /app
CMD ["./client"]
